"""
train_intent.py — Fine-tune MiniLM + Linear head on real HuggingFace dataset.

Uses dataset/labeled_dataset.json (generated by prepare_dataset.py)

What happens here (Deep Learning):
  • Forward pass: text → MiniLM embeddings → Linear head → logits
  • Loss:         CrossEntropyLoss (softmax + negative log-likelihood)
  • Backward:     loss.backward() → gradients flow through Linear layers
  • Update:       Adam optimizer steps on Linear weights
  • MiniLM:       frozen (we train only the classification head)

Run:
  python train_intent.py

Output:
  models/intent_classifier.pt
"""

import os
import sys
import json
import random
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from backend.nlp.intent_model import IntentClassifier

# ── Config ──────────────────────────────────────────────────
DATASET_PATH  = "dataset/labeled_dataset.json"
EPOCHS        = 40
BATCH_SIZE    = 32
LEARNING_RATE = 2e-4
HIDDEN_DIM    = 128
DROPOUT       = 0.1
SAVE_PATH     = "models/intent_classifier.pt"
if not torch.cuda.is_available():
    raise RuntimeError("GPU not found! In Colab: Runtime → Change runtime type → T4 GPU → Save")
DEVICE        = torch.device("cuda")
# ─────────────────────────────────────────────────────────────

INTENT_LABELS = ["COUNT", "AVERAGE", "TOP_N", "BOTTOM_N", "FILTER_LT", "FILTER_GT", "SELECT"]
LABEL2ID      = {l: i for i, l in enumerate(INTENT_LABELS)}
ID2LABEL      = {i: l for i, l in enumerate(INTENT_LABELS)}


class IntentDataset(Dataset):
    def __init__(self, data):
        self.texts  = [d["text"] for d in data]
        self.labels = [LABEL2ID[d["label"]] for d in data]

    def __len__(self): return len(self.texts)
    def __getitem__(self, idx): return self.texts[idx], self.labels[idx]


def collate_fn(batch):
    texts, labels = zip(*batch)
    return list(texts), torch.tensor(labels, dtype=torch.long)


def train():
    print(f"Device : {DEVICE}")
    if DEVICE.type == "cuda":
        print(f"GPU    : {torch.cuda.get_device_name(0)}")

    # Load dataset
    with open(DATASET_PATH) as f:
        data = json.load(f)
    random.shuffle(data)

    split     = int(0.9 * len(data))
    train_data = data[:split]
    val_data   = data[split:]
    print(f"Train  : {len(train_data)} | Val: {len(val_data)}\n")

    train_loader = DataLoader(IntentDataset(train_data), batch_size=BATCH_SIZE, shuffle=True,  collate_fn=collate_fn)
    val_loader   = DataLoader(IntentDataset(val_data),   batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn)

    # Model
    model = IntentClassifier(num_classes=len(INTENT_LABELS), hidden_dim=HIDDEN_DIM, dropout=DROPOUT).to(DEVICE)

    # Freeze MiniLM
    for p in model.encoder.parameters():
        p.requires_grad = False

    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total     = sum(p.numel() for p in model.parameters())
    print(f"Trainable params : {trainable:,}  (frozen MiniLM: {total-trainable:,})\n")

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LEARNING_RATE)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.5)

    print(f"{'Epoch':>6}  {'Train Loss':>11}  {'Train Acc':>10}  {'Val Acc':>8}")
    print("=" * 50)

    best_val_acc = 0.0

    for epoch in range(1, EPOCHS + 1):
        # ── Train ──
        model.train()
        t_loss, t_correct, t_total = 0, 0, 0
        for texts, labels in train_loader:
            labels = labels.to(DEVICE)
            emb    = model.encode_text(texts, DEVICE)
            logits = model(emb)
            loss   = criterion(logits, labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            t_loss    += loss.item() * len(texts)
            t_correct += (torch.argmax(logits, 1) == labels).sum().item()
            t_total   += len(texts)

        # ── Validate ──
        model.eval()
        v_correct, v_total = 0, 0
        with torch.no_grad():
            for texts, labels in val_loader:
                labels = labels.to(DEVICE)
                emb    = model.encode_text(texts, DEVICE)
                logits = model(emb)
                v_correct += (torch.argmax(logits, 1) == labels).sum().item()
                v_total   += len(texts)

        scheduler.step()

        avg_loss  = t_loss / t_total
        train_acc = t_correct / t_total * 100
        val_acc   = v_correct / v_total * 100

        print(f"{epoch:>6}  {avg_loss:>11.4f}  {train_acc:>9.1f}%  {val_acc:>7.1f}%")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            os.makedirs(os.path.dirname(SAVE_PATH), exist_ok=True)
            torch.save({
                "model_state_dict": model.state_dict(),
                "label2id": LABEL2ID,
                "id2label": ID2LABEL,
                "hidden_dim": HIDDEN_DIM,
                "num_classes": len(INTENT_LABELS),
            }, SAVE_PATH)

    print("=" * 50)
    print(f"\nBest Val Accuracy : {best_val_acc:.1f}%")
    print(f"Model saved       → {SAVE_PATH}")

    # Quick sample predictions
    print("\nSample predictions:")
    samples = [
        "how many students are there",
        "show top 5 students by cgpa",
        "students with attendance below 75",
        "average cgpa of all students",
        "list all CSE students",
        "students with cgpa above 8",
        "worst 3 students by marks",
    ]
    for text in samples:
        lid, conf = model.predict(text, DEVICE)
        print(f"  [{ID2LABEL[lid]:12s} {conf*100:5.1f}%]  {text}")


if __name__ == "__main__":
    train()
